"""100 ridiculous retoss excuses (ported from vault toss-excuses.md)."""
from __future__ import annotations

import random

EXCUSES: list[str] = [
    "The coin rolled into the gutter. Adieu, sweet metal disc.",
    "A pigeon thought it was a snack and made off with it.",
    "The coin landed on its edge and refuses to fall over out of pride.",
    "The umpire blinked at the wrong moment. Toss invalidated.",
    "A stray cat decided the coin was a toy. Cat won.",
    "The coin spun for so long it achieved enlightenment.",
    "A sudden breeze carried the coin into the next time zone.",
    "The coin slipped into a glass of water — too soggy to call.",
    "The umpire dropped the coin under a vending machine. Lost forever.",
    "The coin, on reflection, identified as a button. No longer eligible.",
    "A small dog mistook the coin for a treat. He looks pleased.",
    "The coin landed perfectly between heads and tails. Quantum.",
    "The coin teleported. We don't make the rules.",
    "A tax inspector confiscated the coin pending paperwork.",
    "Lightning struck the coin. Now it's a tiny puddle of metal.",
    "A toddler ate the coin. The toddler is fine.",
    "The coin landed on a pizza box and is now considered a topping.",
    "A crow picked up the coin, looked unimpressed, and flew off.",
    "The coin slipped into a parallel dimension.",
    "The coin rolled into a sewer and emerged as a turtle's accessory.",
    "The umpire's dog brought the coin back wet and proud.",
    "The coin caught fire mid-air. Reasons unknown.",
    "A magician walked past. The coin is now in someone's ear.",
    "The coin landed in someone's coffee. The toss is now decaf.",
    "A seagull abducted the coin with mafia-like efficiency.",
    "The coin landed on the umpire's bald spot. Result inconclusive.",
    "A skateboarder grinded over the coin and snapped it.",
    "The coin was hit by a stray cricket ball. Irony noted.",
    "The coin landed in wet cement. See you in 2034.",
    "A snake ate the coin. It's now slightly shinier.",
    "The coin disintegrated upon learning the match format.",
    "A wandering wizard turned the coin into a frog. Frog requests retoss.",
    "The umpire sneezed. Coin: gone.",
    "The coin rolled into a mousehole and joined a small fortune.",
    "A drone delivered the coin to the wrong address.",
    "The coin landed on a chameleon. We can't find either.",
    "A dust devil scooped up the coin and claimed ownership.",
    "The coin began reciting Shakespeare. We're listening, actually.",
    "The coin landed in soup. Whose soup? Unclear.",
    "A vulture circled, assuming the coin was dying.",
    "The coin landed on a rolling cricket bat and rolled away forever.",
    "Time briefly skipped. The coin missed its own toss.",
    "A philosophical squirrel argued the coin is a social construct.",
    "The coin slipped through a crack in spacetime.",
    "The umpire's hand cramped. Coin sent into low orbit.",
    "The coin landed on its side and refuses to commit.",
    "A passing mathematician proved this toss never happened.",
    "A frog with surprising reflexes caught the coin mid-air.",
    "The coin became too embarrassed to land. Still spinning.",
    "A wizard's apprentice was practicing summoning. Coin: gone.",
    "The coin landed in a mug of tea. The British have claimed it.",
    "The coin developed feelings and asked for personal space.",
    "An octopus snatched the coin. Don't ask how.",
    "The coin landed on a soap bubble and floated away.",
    "The umpire forgot which side was heads. Existential crisis.",
    "The coin landed in a pigeon's nest. It has children now.",
    "A breeze nudged the coin into a storm drain. Goodnight, sweet prince.",
    "The coin became one with the asphalt.",
    "The coin landed in the cricket bag and is now the team mascot.",
    "Ants — many ants — carried the coin off in formation.",
    "The coin landed on a ceiling fan blade. Currently at 1200 RPM.",
    "A toddler grabbed the coin. The toddler is now the umpire.",
    "The coin slipped into the umpire's pocket and won't come out.",
    "Crows are placing bets on the coin in their nest.",
    "The umpire dropped his glasses on the coin. Both gone.",
    "A passing mime caught the coin. Or didn't. Hard to tell.",
    "The coin landed on a wet leaf and slid into oblivion.",
    "The coin tossed itself. An inquiry has been launched.",
    "The coin is heads-up and tails-up simultaneously. Quantum coin.",
    "A magpie stole the coin. Birds, man.",
    "The umpire's beard caught the coin. We can't extract it.",
    "The coin landed on a banana peel and slid into the bushes.",
    "A passing detective took the coin as evidence.",
    "The coin entered a fingernail-sized black hole.",
    "The coin's serial number was cursed. Replacing.",
    "A yogi balanced the coin on his nose and strolled off.",
    "The coin landed on the scoreboard and stuck there.",
    "The umpire scratched a lottery ticket with the coin and won. Match cancelled.",
    "The coin gained sentience and declined to participate.",
    "A passing chef seasoned the coin. Now it's salty.",
    "The coin landed in a passing convertible's cupholder.",
    "A statue's pigeon left a tribute on the coin. Tarnished.",
    "The coin slipped between the floorboards. Bring a saw.",
    "A passing accountant rounded the coin out of existence.",
    "The coin became part of a magician's grand finale.",
    "A flamingo ate the coin. It's now pink, neither heads nor tails.",
    "The umpire flipped so hard the coin punched a hole in the sky.",
    "The coin landed in a treasure chest and triggered a side quest.",
    "A passing librarian shushed the coin. It hasn't made a sound since.",
    "The coin landed on a mole's burrow. Mole requests retoss.",
    "The coin landed, stood up, and walked away.",
    "The coin demanded a translator before continuing.",
    "A scientist measured the coin. Now we don't know its position.",
    "The coin landed in someone's open book. Currently page 37.",
    "A vacuum cleaner appeared at exactly the wrong time.",
    "The coin was elected mayor of a small town and is unreachable.",
    "The umpire forgot the rules of cricket. Also this excuse.",
    "The coin discovered jazz and won't commit to a binary outcome.",
    "A dog buried the coin. We respect his commitment.",
    "The coin landed perfectly, but the umpire was on his phone.",
]

FALLBACK_LINE = "The coin has had enough. Just calling heads-or-tails."


def random_excuse(seen: set[str] | None = None) -> str:
    """Pick a random excuse, avoiding back-to-back repeats if `seen` provided."""
    if seen is None or len(seen) >= len(EXCUSES) - 1:
        return random.choice(EXCUSES)
    available = [e for e in EXCUSES if e not in seen]
    return random.choice(available) if available else random.choice(EXCUSES)


assert len(EXCUSES) == 100, f"expected 100 excuses, got {len(EXCUSES)}"
